apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: staging-postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: kerosene-postgres-bootstrap
                  key: bootstrap-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kerosene-postgres-bootstrap
                  key: bootstrap-password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: kerosene-core-db-secrets
                  key: jdbc-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kerosene-core-db-secrets
                  key: application-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kerosene-core-db-secrets
                  key: application-password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfe-service
spec:
  template:
    spec:
      containers:
        - name: kfe-service
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: kerosene-kfe-db-secrets
                  key: jdbc-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kerosene-kfe-db-secrets
                  key: application-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kerosene-kfe-db-secrets
                  key: application-password
