apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policies/default-deny.yaml
  - policies/allow-dns-egress.yaml
  - policies/allow-observability-scrape.yaml
  - dependency-services
  - server
  - kfe-service
  - mpc-sidecar
  - web-page
labels:
  - pairs:
      app.kubernetes.io/part-of: kerosene
