apiVersion: v1
kind: ServiceAccount
metadata:
  name: kfe-service
  labels:
    app.kubernetes.io/name: kfe-service
    app.kubernetes.io/component: financial-engine
automountServiceAccountToken: false
