apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  template:
    spec:
      containers:
        - name: vault
          env:
            - name: VAULT_HEALTH_PROBE_URL
              valueFrom:
                configMapKeyRef:
                  name: vault-health-probe
                  key: local-health-url
                  optional: false
          readinessProbe:
            httpGet: null
            tcpSocket: null
            exec:
              command: [/usr/local/bin/kerosene-vault, --health-probe]
            periodSeconds: 15
            timeoutSeconds: 6
            failureThreshold: 3
