apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: local-ha-allow-tor-egress
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - tor-wvo
          - tor-iw5
          - tor-ltv
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
