apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mpc-sidecar
spec:
  volumeClaimTemplates:
    - metadata:
        name: encrypted-shards
      spec:
        storageClassName: local-luks-encrypted
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 25Gi
