apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  KEROSENE_RUNTIME_ROLE: "core-service"
  REGION: "PROD"
  AUDIT_SOLVENCY_ENFORCED: "true"
  RELEASE_ATTESTATION_REQUIRED: "true"
  RELEASE_REMOTE_ATTESTATION_ENABLED: "true"
  SERVER_SHUTDOWN: "graceful"
  SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE: "45s"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kfe-service-config
data:
  SPRING_PROFILES_ACTIVE: "prod,kfe"
  REGION: "PROD"
  AUDIT_SOLVENCY_ENFORCED: "true"
  RELEASE_ATTESTATION_REQUIRED: "true"
  RELEASE_REMOTE_ATTESTATION_ENABLED: "true"
  SERVER_SHUTDOWN: "graceful"
  SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE: "45s"
