apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kerosene-staging-vault
resources:
  - namespace.yaml
  - vault.yaml
  - tor.yaml
  - network-policy.yaml
labels:
  - pairs:
      app.kubernetes.io/environment: staging
images:
  - name: kerosene/vault
    newTag: staging
  - name: kerosene/tor
    newTag: staging
