apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

# TRANSFER_PENDING
# Source:
# - backend/kerosene-infrastructure/k8s/overlays/local-ha/*tor*.yaml
# - backend/kerosene/deploy/tor/*
resources: []
