apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kerosene-staging
resources:
  - ../../base
  - namespace.yaml
labels:
  - pairs:
      app.kubernetes.io/environment: staging
images:
  - name: kerosene/kfe-service
    newTag: staging
  - name: kerosene/server
    newTag: staging
  - name: kerosene/mpc-sidecar
    newTag: staging
  - name: kerosene/web-page
    newTag: staging
patches:
  - path: patch-staging.yaml
