apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kerosene-staging
resources:
  - ../../base
  - namespace.yaml
  - vault-1-deployment.yaml
  - vault-2-deployment.yaml
  - vault-3-deployment.yaml
  - vault-services.yaml
  - vault-network-policy.yaml
  - vault-prerequisites.yaml
  - staging-runtime.yaml
  - staging-onion.yaml
labels:
  - pairs:
      app.kubernetes.io/environment: staging
images:
  - name: kerosene/kfe-service
    newTag: staging
  - name: kerosene/server
    newTag: staging
  - name: kerosene/web-page
    newTag: staging
  - name: kerosene/vault
    newTag: staging
  - name: kerosene/tor
    newTag: staging
patches:
  - path: patch-staging.yaml
