apiVersion: v1
kind: Service
metadata:
  name: vault-1
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-1
    app.kubernetes.io/component: vault-mesh
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /v1/metrics
    prometheus.io/port: "7801"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-1
  ports:
    - name: http
      port: 7801
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vault-2
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-2
    app.kubernetes.io/component: vault-mesh
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /v1/metrics
    prometheus.io/port: "7801"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-2
  ports:
    - name: http
      port: 7801
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vault-3
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-3
    app.kubernetes.io/component: vault-mesh
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /v1/metrics
    prometheus.io/port: "7801"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-3
  ports:
    - name: http
      port: 7801
      targetPort: http
      protocol: TCP
